### route to create a task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "name": "Task 1",
  "quantity": 12
}

### route to update a task

PUT http://localhost:3000/tasks/c5204281-14b3-4b43-8f49-930e00c1fc15
Content-Type: application/json

{
  "name": "Task 3",
  "quantity": 15
}

### route to get all tasks

GET http://localhost:3000/tasks

###

GET http://localhost:3000/tasks/getByUserId/86faaea8-45d6-4009-9bfc-4b3e1287b05c

###

DELETE http://localhost:3000/tasks

###

POST http://localhost:3000/attachments
Content-Type: application/json

{
  "name": "teste",
  "description": "testqar",
  "deadline": "2024-12-01T00:00:00Z"
}

###

POST http://localhost:3000/tasks/createMany
Content-Type: application/json

{
  "tasks": [
    { "name": "Instalação/atualização do desktop", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Não envia mensagem de saudação", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Não envia mensagem de cashback", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Não envia mensagem de status", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Robô não carrega (não gerou QRCODE)", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Robô leu o QRCODE mas não carrega", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Configurar e/ou instalar impressora", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Encaminhar acesso", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Tenta reproduzir bug", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Contratar novo painel", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Renovação painel", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Reativação de painel", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Venda de cardápio", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Preenchimento / ajuda com o menu 'meu perfil'", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Montagem de cardápio ou ajuda cardápio", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Configurar impressora do celular/computador", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Configurar mensagem automática no celular", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Preenchimento / ajuda formas de pagamento (Online/manual)", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Gerar QRCODE para o cliente", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Questão NFC-e", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Sugestão", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Cliente informa que os itens não estão aparecendo (disponibilidade)", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Redefinir senha de acesso / financeira", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Configurações de mesas / encomendas/pdv", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Pedido teste / PDV (Passo 5)", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Abertura de card", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Cancelamento", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Gerar boleto ou enviar pix para pagamento", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Confirmação de pagamento (cliente enviou comprovante)", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" },
    { "name": "Liberação de painel (arquivo não encontrado)", "quantity": 0, "userId": "b7eccff5-43c4-4eff-bac4-14f87b4389eb" }
  ]
}
